[[Channels]]
URL = "https://www.youtube.com/@HundredRabbits/videos"
Name = "100r"

[[Channels]]
URL = "https://www.youtube.com/@AdamOndra/videos"
Name = "adam ondra"

[[Channels]]
URL = "https://www.youtube.com/@BenEater/videos"
Name = "ben eater"

[[Channels]]
URL = "https://www.youtube.com/@BJGpixel/videos"
Name = "brandon james greer"

[[Channels]]
URL = "https://www.youtube.com/@elliotttstrawser/videos"
Name = "elliott"

[[Channels]]
URL = "https://www.youtube.com/@GMTK/videos"
Name = "game makers toolkit"

[[Channels]]
URL = "https://www.youtube.com/@Gdquest/videos"
Name = "gdquest"

[[Channels]]
URL = "https://www.youtube.com/@GearSkeptic/videos"
Name = "gear skeptic"

[[Channels]]
URL = "https://www.youtube.com/@GxAce/videos"
Name = "gxace"

[[Channels]]
URL = "https://www.youtube.com/@JimiSol/videos"
Name = "jimi"

[[Channels]]
URL = "https://www.youtube.com/@JohnZahorian/videos"
Name = "johnz"

[[Channels]]
URL = "https://www.youtube.com/@JupiterHikes/videos"
Name = "jupiter"

[[Channels]]
URL = "https://www.youtube.com/@mellowclimbing/videos"
Name = "mellow"

[[Channels]]
URL = "https://www.youtube.com/@NCommander/videos"
Name = "ncommander"

[[Channels]]
URL = "https://www.youtube.com/@NotJustBikes/videos"
Name = "not just bikes"

[[Channels]]
URL = "https://www.youtube.com/@SebastianLague/videos"
Name = "sebastian lague"

[[Channels]]
URL = "https://www.youtube.com/@Shaun_vids/videos"
Name = "shaun"

[[Channels]]
URL = "https://www.youtube.com/@t3ssel8r/videos"
Name = "t3ssel8r"

[[Channels]]
URL = "https://www.youtube.com/@tom7/videos"
Name = "tom7"

[[Channels]]
URL = "https://www.youtube.com/@Zaypixel/videos"
Name = "zaypixel"
